Profile page
cssgunc/CSPortal pull request #31
Opened 2021-04-12 19:08 UTC by eden0606

pich and i finished up basic features for the frontend from figma.

2021-04-12 22:58 UTC, Dafondo requested changes
Looks really good! Can we add a "Cancel" button on the edit profile view?

2021-04-13 00:16 UTC, eden0606 commented
added it!

2021-04-19 22:23 UTC, pichhim commented
Looks good to merge!

2021-04-26 15:15 UTC, Dafondo approved these changes

2021-04-26 15:15 UTC, merged